// ETF轮动 快捷指令纯文本版 (Scriptable, iOS) — 输出纯文本，适合直接发邮件正文
const ETF_LIST=[{code:"510300",name:"沪深",market:"sh"},{code:"159915",name:"创业",market:"sz"},{code:"513100",name:"纳指",market:"sh"},{code:"518880",name:"黄金",market:"sh"}];
const N=25,VOL_WINDOW=20,TRADING_DAYS=250,FETCH_DAYS=100,TIMEOUT=8;
const AVG_VOL_THRESHOLD=0.40,TREND_THRESHOLD=95.0,HOLD_VOL_THRESHOLD_B=0.24,HOLD_VOL_THRESHOLD_C=0.40,AVG_VOL_THRESHOLD_C=0.30;
const sleep=s=>new Promise(r=>setTimeout(r,s*1000));
async function fetchEM(code,market){const secid=(market==="sh"?"1.":"0.")+code;const url=`https://push2his.eastmoney.com/api/qt/stock/kline/get?secid=${secid}&fields1=f1,f2,f3&fields2=f51,f52,f53,f54,f55,f56&klt=101&fqt=1&end=20500101&lmt=${FETCH_DAYS}`;const req=new Request(url);req.timeoutInterval=TIMEOUT;req.headers={"User-Agent":"Mozilla/5.0","Referer":"https://quote.eastmoney.com/"};const d=await req.loadJSON();if(!d||!d.data||!d.data.klines)return null;const v=d.data.klines.map(k=>k.split(",")).filter(r=>parseFloat(r[5])>0).map(r=>({day:r[0],open:parseFloat(r[1]),close:parseFloat(r[2]),high:parseFloat(r[3]),low:parseFloat(r[4]),volume:parseFloat(r[5])}));return v.length>=60?v:null;}
async function fetchSina(code,market){const url=`https://money.finance.sina.com.cn/quotes_service/api/json_v2.php/CN_MarketData.getKLineData?symbol=${market}${code}&datalen=${FETCH_DAYS}&scale=240&ma=no`;const req=new Request(url);req.timeoutInterval=TIMEOUT;req.headers={"User-Agent":"Mozilla/5.0","Referer":"https://finance.sina.com.cn"};const data=await req.loadJSON();if(!Array.isArray(data)||data.length<60)return null;const v=data.filter(d=>parseFloat(d.volume)>0).map(d=>({day:d.day||d.date,open:parseFloat(d.open),close:parseFloat(d.close),high:parseFloat(d.high),low:parseFloat(d.low),volume:parseFloat(d.volume)}));return v.length>=60?v:null;}
async function fetchKlines(code,market){for(let a=0;a<2;a++){try{const r=await fetchEM(code,market);if(r)return r;}catch(e){}if(a<1)await sleep(1);}try{const r=await fetchSina(code,market);if(r)return r;}catch(e){}return null;}
function calcScore(c){c=c.slice(-N);if(c.length<N||Math.min(...c)<=0)return 0;const y=c.map(x=>Math.log(x)),x=Array.from({length:N},(_,i)=>i),n=x.length,sx=x.reduce((a,b)=>a+b,0),sy=y.reduce((a,b)=>a+b,0),sxx=x.reduce((a,b)=>a+b*b,0),sxy=x.reduce((a,b,i)=>a+b*y[i],0);const denom=n*sxx-sx*sx;if(denom===0)return 0;const slope=(n*sxy-sx*sy)/denom,intercept=(sy-slope*sx)/n,annual=Math.exp(slope*TRADING_DAYS)-1,yP=x.map(xi=>slope*xi+intercept),ym=sy/n,ssr=y.reduce((a,_,i)=>a+(y[i]-yP[i])**2,0),sst=y.reduce((a,yi)=>a+(yi-ym)**2,0),r2=sst>0?1-ssr/sst:0;return annual*r2;}
function calcVol20(closes){if(closes.length<VOL_WINDOW+1)return 0;const rec=closes.slice(-(VOL_WINDOW+1)),rets=[];for(let i=1;i<rec.length;i++)if(rec[i-1]>0)rets.push((rec[i]-rec[i-1])/rec[i-1]);if(rets.length<VOL_WINDOW)return 0;const m=rets.reduce((a,b)=>a+b,0)/rets.length,v=rets.reduce((a,b)=>a+(b-m)**2,0)/(rets.length-1);return Math.sqrt(v)*Math.sqrt(TRADING_DAYS);}
function tdxSma(v,n,m){const o=new Array(v.length).fill(NaN);let y=NaN;for(let i=0;i<v.length;i++){if(isNaN(v[i])){o[i]=y;continue;}if(isNaN(y))y=v[i];else y=(v[i]*m+y*(n-m))/n;o[i]=y;}return o;}
function calcTrend(h,l,c){const n=c.length;if(n<55)return 50;const rsv=[];for(let i=0;i<n;i++){if(i<54){rsv.push(50);continue;}let llv=Infinity,hh=-Infinity;for(let j=i-54;j<=i;j++){if(l[j]<llv)llv=l[j];if(h[j]>hh)hh=h[j];}rsv.push(hh===llv?50:(c[i]-llv)/(hh-llv)*100);}const s5=tdxSma(rsv,5,1),s53=tdxSma(s5,3,1),v11=[];for(let i=0;i<n;i++)v11.push(!isNaN(s5[i])&&!isNaN(s53[i])?3*s5[i]-2*s53[i]:50);const ema=new Array(n).fill(NaN);ema[0]=v11[0];const al=0.5;for(let i=1;i<n;i++)ema[i]=al*v11[i]+(1-al)*ema[i-1];return ema[n-1];}
function checkRisk(avg,hv,ht){const t=[];if(avg>AVG_VOL_THRESHOLD)t.push("① 等权vol20="+(avg*100).toFixed(1)+"%>"+(AVG_VOL_THRESHOLD*100)+"%");if(ht>TREND_THRESHOLD&&hv>HOLD_VOL_THRESHOLD_B)t.push("② 趋势="+ht.toFixed(1)+">"+TREND_THRESHOLD+"且持有vol="+(hv*100).toFixed(1)+"%");if(hv>HOLD_VOL_THRESHOLD_C&&avg>AVG_VOL_THRESHOLD_C)t.push("③ 持有vol="+(hv*100).toFixed(1)+"%且均="+(avg*100).toFixed(1)+"%");return{triggered:t.length>0,reasons:t};}
async function run(){let res=await Promise.all(ETF_LIST.map(async(e,i)=>{if(i>0)await sleep(0.1);return{e,raw:await fetchKlines(e.code,e.market)};}));let fail=res.filter(r=>!r.raw);if(fail.length){await sleep(2);const rt=await Promise.all(fail.map(async({e})=>({e,raw:await fetchKlines(e.code,e.market)})));for(const xr of rt){if(xr.raw){const i=res.findIndex(r=>r.e.code===xr.e.code);if(i>=0)res[i].raw=xr.raw;}}}
const vr=[];for(const{e,raw}of res){if(!raw)continue;const c=raw.map(d=>d.close),h=raw.map(d=>d.high),l=raw.map(d=>d.low),d=raw[raw.length-1].day||raw[raw.length-1].date;vr.push({code:e.code,name:e.name,score:calcScore(c),vol:calcVol20(c),trend:calcTrend(h,l,c),price:c[c.length-1],date:d});}
if(!vr.length)return{error:"无数据"};vr.sort((a,b)=>b.score-a.score);const best=vr[0],avg=vr.reduce((a,r)=>a+r.vol,0)/vr.length,rk=checkRisk(avg,best.vol,best.trend);return{results:vr,best,avgVol:avg,triggered:rk.triggered,reasons:rk.reasons,newestDate:vr.map(r=>r.date).sort().pop(),partialFail:vr.length<ETF_LIST.length};}
function formatText(data){const L=[];L.push("━━━━━━━━━━━━");L.push("📅 数据日期: "+data.newestDate);L.push("");if(data.triggered)L.push("🔴 操作: 清仓 ETF, 全仓买逆回购 GC001/R-001");else L.push("🟢 操作: 满仓持有 "+data.best.name+" ("+data.best.code+")");L.push("");if(data.triggered){L.push("⚠️ 风控触发原因:");data.reasons.forEach(r=>L.push("   "+r));}else L.push("✅ 风控未触发, 各项指标正常");L.push("");L.push("📋 动量得分排名:");const medals=["🥇","🥈","🥉","   "];data.results.forEach((r,i)=>{const star=(!data.triggered&&i===0)?" ⬅ 推荐":"";L.push(medals[i]+" "+r.name+" "+(r.score>=0?"+":"")+r.score.toFixed(3)+" "+(r.vol*100).toFixed(1)+"% "+r.trend.toFixed(1)+star);});L.push("");L.push("等权平均 vol20: "+(data.avgVol*100).toFixed(1)+"% (阈值"+(AVG_VOL_THRESHOLD*100)+"%)");if(data.partialFail){L.push("");L.push("⚠️ 注意: 部分标的数据获取失败, 结果仅供参考");}L.push("━━━━━━━━━━━━");return L.join("\n");}
if(config.runsInWidget){
  (async()=>{const data=await run();let title,subtitle,color,body;if(data.error){title="❌ 无数据";subtitle="所有数据源失败";color=Color.gray();body="";}else{title=data.triggered?"🔴 清仓切逆回购":"🟢 持有 "+data.best.name;subtitle=data.newestDate+" · 均="+(data.avgVol*100).toFixed(1)+"%";color=data.triggered?Color.red():Color.green();body=data.results.slice(0,4).map((r,i)=>["🥇","🥈","🥉","  "][i]+r.name+" "+(r.vol*100).toFixed(0)+"%|"+r.trend.toFixed(0)).join("\n");}const w=new ListWidget();w.backgroundColor=color;const t=w.addText(title);t.font=Font.boldSystemFont(16);t.textColor=Color.white();const s=w.addText(subtitle);s.font=Font.systemFont(11);s.textColor=Color.white();if(body){w.addSpacer(4);const b=w.addText(body);b.font=Font.systemFont(10);b.textColor=Color.white();}Script.setWidget(w);Script.complete();})();
}else{
  (async()=>{const d=await run();Script.setShortcutOutput(d.error?"ETF轮动失败："+d.error:formatText(d));Script.complete();})();
}
